version: "3"
services:
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    container_name: api-server
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: app-client
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
